"""empty message

Revision ID: 001e02dd7bdf
Revises: da2212cb995b
Create Date: 2023-07-10 16:26:26.507114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001e02dd7bdf'
down_revision = 'da2212cb995b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=1400),
               existing_nullable=False)

    with op.batch_alter_table('valoracion', schema=None) as batch_op:
        batch_op.alter_column('comentario',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=1500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valoracion', schema=None) as batch_op:
        batch_op.alter_column('comentario',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)

    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=1400),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###
