"""empty message

Revision ID: 449edb544a3f
Revises: 3aee39dd06d0
Create Date: 2023-06-21 17:37:52.053096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449edb544a3f'
down_revision = '3aee39dd06d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('precio', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.drop_column('precio')
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
