"""empty message

Revision ID: 56163a42700e
Revises: 169d0bb271c0
Create Date: 2023-06-14 19:09:32.305708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56163a42700e'
down_revision = '169d0bb271c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cif', sa.String(length=20), nullable=False),
    sa.Column('razon_social', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('poblacion', sa.String(length=40), nullable=False),
    sa.Column('direccion', sa.String(length=60), nullable=False),
    sa.Column('codigo_postal', sa.Integer(), nullable=False),
    sa.Column('datos_bancarios', sa.String(length=30), nullable=True),
    sa.Column('autorizados', sa.String(length=60), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('razon_social'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.Column('descripcion', sa.String(length=140), nullable=False),
    sa.Column('ubicacion', sa.String(length=40), nullable=False),
    sa.Column('fecha_inicio', sa.String(length=10), nullable=False),
    sa.Column('fecha_fin', sa.String(length=10), nullable=False),
    sa.Column('personas', sa.Integer(), nullable=False),
    sa.Column('free', sa.Boolean(), nullable=True),
    sa.Column('importe', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user__empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('pasarela_id', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pasarela_id')
    )
    op.create_table('valoracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('estrellas', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comentario')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dni', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['dni'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('dni')

    op.drop_table('valoracion')
    op.drop_table('factura')
    op.drop_table('user__empresa')
    op.drop_table('evento')
    op.drop_table('empresa')
    # ### end Alembic commands ###
