"""empty message

Revision ID: bc872a0fd1bd
Revises: e8acbc07fc95
Create Date: 2023-06-21 16:49:57.627104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc872a0fd1bd'
down_revision = 'e8acbc07fc95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user__empresa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user__empresa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name='user__empresa_empresa_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user__empresa_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user__empresa_pkey')
    )
    op.drop_table('user_empresa')
    # ### end Alembic commands ###
