"""empty message

Revision ID: da2212cb995b
Revises: eac4d7a75e63
Create Date: 2023-07-07 19:22:34.917095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2212cb995b'
down_revision = 'eac4d7a75e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=400),
               existing_nullable=True)

    with op.batch_alter_table('valoracion', schema=None) as batch_op:
        batch_op.alter_column('comentario',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valoracion', schema=None) as batch_op:
        batch_op.alter_column('comentario',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
